### ISSUE TITLE
Subdirectories with config files

### ISSUE THREAD

**Issue by alexlopespereira** [JacFearsome/nginx-config-editor#3]
I created a sub-directory (e.g. config_users) inside my config_folder and put some config files there. When I started the application I could not see/edit the config files that are inside that sub-directory.
 
Is it possible show those files by changing the config.json file ? Or would it need some javascript coding?

**Comment by JacFearsome** [comment]
Right now it does not read subdirectories, but I will modify the code to recursively search the directory and add all configs to the list.  Probably won't take me very long, and I will push a commit sometime later today most likely.

**Comment by alexlopespereira** [comment]
Hi @JacFearsome 
Is there any update on this issue?

**Comment by JacFearsome** [comment]
Hey Alex,
I apologize for the delay, I've had a lot going on.  Starting work on this now.

**Comment by JacFearsome** [comment]
Hey @alexlopespereira just wanted to let you know this is still on my task list, have been quite busy.  Will also look into the other two issues as well.

**Comment by JacFearsome** [comment]
![recursivexample](https://user-images.githubusercontent.com/20714325/64224534-ea756a80-cea5-11e9-9b0c-a97031519f35.png)
Hey I finally sat down to tackle this one, and I created sub directories within the config folder.  They show up just fine as shown.

**Comment by alexlopespereira** [comment]
Very nice. Thank you.
