### ISSUE TITLE
Changing localhost to 0.0.0.0 in config.json

### ISSUE THREAD

**Issue by alexlopespereira** [JacFearsome/nginx-config-editor#4]
I would like to suggest to change this line of the config.json file:
    "address" : "localhost"
By this line:
    "address" : "0.0.0.0"

Because in a container it was not accepting connections until I made this changing.

**Comment by JacFearsome** [comment]
@alexlopespereira  Will make this change!

**Comment by JacFearsome** [comment]
https://github.com/JacFearsome/nginx-config-editor/commit/b0af571c18f53d2f1d4d761a0d337d9119c3a17f
