### ISSUE TITLE
Restrict access to the config-editor application

### ISSUE THREAD

**Issue by alexlopespereira** [JacFearsome/nginx-config-editor#5]
What would be the best way to restrict access to this application only to authenticated users?

**Comment by JacFearsome** [comment]
@alexlopespereira You should look into basic http auth, you can actually add a couple lines to the nginx reverse proxy that add auth to that page.  You will need to create a .htpasswd file which you can do with a cmd line tool.

**Comment by alexlopespereira** [comment]
This solves my questions.
